import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from './components/providers'
import Navbar from './components/navbar/Navbar'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Complete Authentication',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ToastContainer/>
          <Navbar/>
        {children}
        </AuthProvider>
        </body>
    </html>
  )
}
